In [1]:
import sklearn
from sklearn.datasets import load_files

In [2]:
moviedir = r'.\movie_reviews'
# loading all files. 
movie = load_files(moviedir, shuffle=True)

print(movie.keys())
print(len(movie.data))

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])
2000


In [3]:
print(movie.filenames)

['.\\movie_reviews\\neg\\cv405_21868.txt'
 '.\\movie_reviews\\pos\\cv190_27052.txt'
 '.\\movie_reviews\\pos\\cv132_5618.txt' ...
 '.\\movie_reviews\\pos\\cv653_19583.txt'
 '.\\movie_reviews\\neg\\cv559_0057.txt'
 '.\\movie_reviews\\neg\\cv684_12727.txt']


In [4]:
print(movie.target_names)
print(movie.target)
print(movie.target.size)

['neg', 'pos']
[0 1 1 ... 1 0 0]
2000


In [5]:
print(movie.data[1])
print(movie.target[1])

b"good films are hard to find these days . \ngreat films are beyond rare . \nproof of life , russell crowe's one-two punch of a deft kidnap and rescue thriller , is one of those rare gems . \na taut drama laced with strong and subtle acting , an intelligent script , and masterful directing , together it delivers something virtually unheard of in the film industry these days , genuine motivation in a story that rings true . \nconsider the strange coincidence of russell crowe's character in proof of life making the moves on a distraught wife played by meg ryan's character in the film -- all while the real russell crowe was hitching up with married woman meg ryan in the outside world . \ni haven't seen this much chemistry between actors since mcqueen and mcgraw teamed up in peckinpah's masterpiece , the getaway . \nbut enough with the gossip , let's get to the review . \nthe film revolves around the kidnapping of peter bowman ( david morse ) , an american engineer working in south america

# A detour: try out CountVectorizer & TF-IDF
extractig features from text data per sample

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk

In [7]:
# Turn off pretty printing of jupyter notebook... it generates long lines
%pprint

Pretty printing has been turned OFF


In [8]:
# Example: let's ake Three tiny "documents"
docs = ['A rose is a rose is a rose is a rose.',
        'Oh, what a fine day it is.',
        "A day ain't over till it's truly over."]

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidVectorizer = TfidfVectorizer(max_df=0.7)
docs_tfid_vector = tfidVectorizer.fit_transform(docs)
print(docs_tfid_vector.toarray())
print(tfidVectorizer.get_feature_names())
print(tfidVectorizer.vocabulary_)
print(tfidVectorizer.idf_)
print(tfidVectorizer.stop_words_)

[[0.         0.         0.         0.49546155 0.         0.
  0.         0.86862987 0.         0.         0.        ]
 [0.         0.34949812 0.45954803 0.34949812 0.34949812 0.45954803
  0.         0.         0.         0.         0.45954803]
 [0.35013871 0.26628951 0.         0.         0.26628951 0.
  0.70027741 0.         0.35013871 0.35013871 0.        ]]
['ain', 'day', 'fine', 'is', 'it', 'oh', 'over', 'rose', 'till', 'truly', 'what']
{'rose': 7, 'is': 3, 'oh': 5, 'what': 10, 'fine': 2, 'day': 1, 'it': 4, 'ain': 0, 'over': 6, 'till': 8, 'truly': 9}
[1.69314718 1.28768207 1.69314718 1.28768207 1.28768207 1.69314718
 1.69314718 1.69314718 1.69314718 1.69314718 1.69314718]
set()


# Back to real data: movie reviews

In [12]:
# Split data into training and test sets
from sklearn.model_selection import train_test_split
docs_train, docs_test, y_train, y_test = train_test_split(movie.data, movie.target, 
                                                          test_size = 0.20, random_state = 12)

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
movie_tfidVectorizer = TfidfVectorizer(stop_words = 'english', max_df=0.5, ngram_range = (1,1), max_features=5000)
docs_train_tfidVectors = movie_tfidVectorizer.fit_transform(docs_train)
print(docs_train_tfidVectors.toarray())

print(movie_tfidVectorizer.get_feature_names())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.07806992 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.08780026 0.         0.         ... 0.         0.         0.        ]]
['000', '10', '100', '11', '12', '13', '13th', '14', '15', '16', '17', '18', '1960', '1960s', '1970s', '1980', '1980s', '1981', '1984', '1985', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '19th', '20', '200', '2000', '2001', '20th', '24', '25', '30', '40', '50', '54', '60', '60s', '70', '70s', '80', '80s', '8mm', '90', '90s', '_the', 'abandon', 'abandoned', 'abilities', 'ability', 'able', 'aboard', 'absent', 'absolute', 'absolutely', 'absurd', 'abuse', 'abyss', 'academy', 'accent', 'accents', 'accep

In [28]:
help(TfidfVectorizer)

Help on class TfidfVectorizer in module sklearn.feature_extraction.text:

class TfidfVectorizer(CountVectorizer)
 |  TfidfVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, analyzer='word', stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.float64'>, norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False)
 |  
 |  Convert a collection of raw documents to a matrix of TF-IDF features.
 |  
 |  Equivalent to :class:`CountVectorizer` followed by
 |  :class:`TfidfTransformer`.
 |  
 |  Read more in the :ref:`User Guide <text_feature_extraction>`.
 |  
 |  Parameters
 |  ----------
 |  input : {'filename', 'file', 'content'}, default='content'
 |      - If `'filename'`, the sequence passed as an argument to fit is
 |        expected to be a list of filenames that need reading to fetc

In [15]:
print(movie_tfidVectorizer.vocabulary_)

{'buddy': 580, 'comedy': 866, 'fish': 1728, 'water': 4861, 'nature': 3019, 'tale': 4420, 'meet': 2828, 'nearly': 3028, 'interesting': 2313, 'fact': 1611, 'phil': 3299, 'paul': 3256, 'walker': 4823, 'steve': 4260, 'van': 4751, 'twin': 4656, 'sons': 4144, 'famous': 1637, 'millionaire': 2886, 'eric': 1507, 'wants': 4839, 'perfect': 3272, 'fortune': 1797, 'instead': 2294, 'set': 3970, 'straight': 4281, 'strict': 4292, 'boot': 502, 'camp': 633, 'pair': 3214, 'inevitably': 2265, 'duo': 1385, 'discover': 1284, 'brothers': 567, 'routine': 3816, 'mistaken': 2914, 'identity': 2209, 'plot': 3359, 'arrive': 274, 'national': 3015, 'park': 3232, 'believed': 426, 'new': 3053, 'home': 2141, 'disappointing': 1278, 'dad': 1090, 'play': 3346, 'actually': 101, 'motives': 2963, 'beautiful': 408, 'jesse': 2394, 'unfortunately': 4700, 'happens': 2033, 'beloved': 432, 'captain': 642, 'douglas': 1333, 'john': 2411, 'problem': 3466, 'week': 4882, 'old': 3150, 'faithful': 1624, 'birthday': 453, 'dogs': 1313, 'th

In [16]:
#print(movie_tfidVectorizer.idf_)
print(movie_tfidVectorizer.stop_words_)

{'allah', 'loading', 'idolizes', 'pilgrims', 'budge', 'hackles', 'woodsboro', 'frighteners', 'clunky', 'basketballs', 'sensationaliztion', 'faceless', 'mahal', 'whacked', 'sharman', 'extremeties', 'forks', 'chalk', 'terrified', 'mathilda', 'zombified', 'spinetinglingly', 'superstars', 'mandatory', 'honeys', 'entails', 'freaky', 'assuming', 'recieves', 'buyer', 'gilles', 'gloopettes', 'saboteur', 'pikachu', 'jobson', 'chronological', 'bawling', 'pasted', 'embers', 'billed', 'preppie', 'titillating', 'landau', 'holler', 'wronged', 'copping', 'oppressive', 'reassessed', 'strewn', 'ernest', 'disapproving', 'erstwhile', 'scrap', 'voted', 'akin', 'wizards', 'ravages', 'plotted', 'stacks', 'classifying', 'waterway', 'bethlehem', 'preparation', 'eponymous', 'tovoli', 'bai', 'oath', 'prancer', 'favours', 'projectionist', 's_funniest_home_videos_', 'extending', 'oasis', 'multiples', 'dollah', 'schenkel', 'prompted', 'rms', 'ballerina', 'bordering', 'remorse', 'posted', 'towne', 'guillotine', 'do

# The feature extraction functions and traning data are ready.
Vectorizer and transformer have been built from the training data
Training data text was also turned into TF-IDF vector form
Next up: test data
You have to prepare the test data using the same feature extraction scheme

In [17]:
# Using the fitted vectorizer and transformer, tranform the test data
docs_test_tfidfvectors = movie_tfidVectorizer.transform(docs_test)

# Training and testing a Naive Bayes classifier

In [18]:
# Now ready to build a classifier. 
# We will use Multinominal Naive Bayes as our model
from sklearn.naive_bayes import MultinomialNB

In [19]:
# Train a Multi Naive Bayes classifier. Again, we call it "fitting"
clf = MultinomialNB()
clf.fit(docs_train_tfidVectors, y_train)

MultinomialNB()

In [20]:
# Predict the Test set results, find accuracy
y_pred = clf.predict(docs_test_tfidfvectors)
sklearn.metrics.accuracy_score(y_test, y_pred)

0.81

In [21]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[175,  31],
       [ 45, 149]], dtype=int64)

In [22]:
# Train a Gaussian Naive Bayes classifier. Again, we call it "fitting"
from sklearn.naive_bayes import GaussianNB
clfG = GaussianNB()
clfG.fit(docs_train_tfidVectors.toarray(), y_train)
# Predict the Test set results, find accuracy
y_pred = clfG.predict(docs_test_tfidfvectors.toarray())
print(sklearn.metrics.accuracy_score(y_test, y_pred))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

0.7


array([[150,  56],
       [ 64, 130]], dtype=int64)

# Trying the classifier on fake movie reviews

In [23]:
# very short and fake movie reviews
reviews_new = ['This movie was excellent', 'Absolute joy ride', 
            'Steven Seagal was terrible', 'Steven Seagal shone through.', 
              'This was certainly a movie', 'Two thumbs up', 'I fell asleep halfway through', 
              "We can't wait for the sequel!!", '!', '?', 'I cannot recommend this highly enough', 
              'instant classic.', 'Steven Seagal was amazing. His performance was Oscar-worthy.',
              'On the whole, Enthavaralaina is a crime horror thriller which fails to create any excitement for the audience. Too many unnecessary scenes, forced emotions, and disappointing narration makes the film go down in no time and ends as a painful watch this weekend.',
              'On the whole, Maharshi is the journey of a man who finds his roots back in his motherland. Who better than Mahesh Babu to portray all this which has been narrated in an emotional manner by Vamsi Paidipally. Top-notch performances, decent humor, relatable social message, and Mahesh’s screen presence are main assets. If you ignore the slow pace and slightly predictable second half, this film has in it to work with a major section of the audience and the holiday summer season will help the film in a big way.']

reviews_new_tfidf = movie_tfidVectorizer.transform(reviews_new)  # turn into tfidf vector

In [24]:
# have classifier make a prediction
pred = clf.predict(reviews_new_tfidf)

In [25]:
# print out results
for review, category in zip(reviews_new, pred):
    print('%r => %s' % (review, movie.target_names[category]))

'This movie was excellent' => pos
'Absolute joy ride' => pos
'Steven Seagal was terrible' => neg
'Steven Seagal shone through.' => neg
'This was certainly a movie' => pos
'Two thumbs up' => pos
'I fell asleep halfway through' => neg
"We can't wait for the sequel!!" => neg
'!' => pos
'?' => pos
'I cannot recommend this highly enough' => pos
'instant classic.' => pos
'Steven Seagal was amazing. His performance was Oscar-worthy.' => neg
'On the whole, Enthavaralaina is a crime horror thriller which fails to create any excitement for the audience. Too many unnecessary scenes, forced emotions, and disappointing narration makes the film go down in no time and ends as a painful watch this weekend.' => neg
'On the whole, Maharshi is the journey of a man who finds his roots back in his motherland. Who better than Mahesh Babu to portray all this which has been narrated in an emotional manner by Vamsi Paidipally. Top-notch performances, decent humor, relatable social message, and Mahesh’s screen 

In [26]:
from sklearn import neighbors, linear_model
from time import time

logistic = linear_model.LogisticRegression()

t0 = time()
print('LogisticRegression score: {}', logistic.fit(docs_train_tfidVectors, y_train).score(docs_test_tfidfvectors, y_test))
print("done in %0.3fs" , (time() - t0))

LogisticRegression score: {} 0.8375
done in %0.3fs 0.04969620704650879


In [27]:
help(sklearn.naive_bayes)

Help on module sklearn.naive_bayes in sklearn:

NAME
    sklearn.naive_bayes

DESCRIPTION
    The :mod:`sklearn.naive_bayes` module implements Naive Bayes algorithms. These
    are supervised learning methods based on applying Bayes' theorem with strong
    (naive) feature independence assumptions.

CLASSES
    _BaseDiscreteNB(_BaseNB)
        BernoulliNB
        CategoricalNB
        ComplementNB
        MultinomialNB
    _BaseNB(sklearn.base.ClassifierMixin, sklearn.base.BaseEstimator)
        GaussianNB
    
    class BernoulliNB(_BaseDiscreteNB)
     |  BernoulliNB(*, alpha=1.0, binarize=0.0, fit_prior=True, class_prior=None)
     |  
     |  Naive Bayes classifier for multivariate Bernoulli models.
     |  
     |  Like MultinomialNB, this classifier is suitable for discrete data. The
     |  difference is that while MultinomialNB works with occurrence counts,
     |  BernoulliNB is designed for binary/boolean features.
     |  
     |  Read more in the :ref:`User Guide <bernoulli

In [ ]:
#Exercises:
# try to improve the MultinomialNB accuracy by playing with the following hyper params:
# max_df
#max_features
#ngram_range - bi, trigrams
#smooth_idf